definitions:
  domain.Product:
    properties:
      code_value:
        type: string
      expiration:
        type: string
      id:
        type: integer
      is_published:
        type: boolean
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  web.errorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  web.response:
    properties:
      data: {}
    type: object
info:
  contact:
    name: API Support
    url: https://developers.ctd.com.ar/support
  description: This API Handle Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.ctd.com.ar/es_ar/terminos-y-condiciones
  title: Products Market
  version: "1.0"
paths:
  /products:
    get:
      description: Get all products from repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
      summary: Get all products
      tags:
      - products
    post:
      description: Create a new product in repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Create a new product
      tags:
      - products
  /products/:id:
    delete:
      description: Delete a product by id in repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Delete a product
      tags:
      - products
    get:
      description: Get a product by Id from repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Get a product by Id
      tags:
      - products
    patch:
      description: Update a product by id in repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Product'
      - description: Product Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Update a product
      tags:
      - products
    put:
      description: Update a product by id in repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Product'
      - description: Product Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Update a product by id
      tags:
      - products
  /products/consumer_price:
    get:
      description: Returns the price of a list of products and the list
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - collectionFormat: csv
        description: List Ids
        in: query
        items:
          type: integer
        name: list
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Returns a price and a list
      tags:
      - products
  /products/search:
    get:
      description: Get  products whose price is greater than a value from repository
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Price Gt
        in: query
        name: priceGt
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Get  products by price
      tags:
      - products
swagger: "2.0"
